type AutoGenerated struct {
	Schema      string `json:"$schema"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Type        string `json:"type"`
	Properties  struct {
		AdditionalRepositories struct {
			Description string   `json:"description"`
			Type        string   `json:"type"`
			Enum        []string `json:"enum"`
		} `json:"additional-repositories"`
		AudioConfig struct {
			Description string `json:"description"`
			Type        string `json:"type"`
			Properties  struct {
				Audio struct {
					Description string   `json:"description"`
					Type        string   `json:"type"`
					Enum        []string `json:"enum"`
				} `json:"audio"`
			} `json:"properties"`
		} `json:"audio_config"`
		Bootloader struct {
			Description string   `json:"description"`
			Type        string   `json:"type"`
			Enum        []string `json:"enum"`
		} `json:"bootloader"`
		Uki struct {
			Description string `json:"description"`
			Type        string `json:"type"`
		} `json:"uki"`
		CustomCommands struct {
			Description string `json:"description"`
			Type        string `json:"type"`
			Items       struct {
				Type string `json:"type"`
			} `json:"items"`
		} `json:"custom-commands"`
		Harddrives struct {
			Description string `json:"description"`
			Type        string `json:"type"`
			Items       struct {
				Type string `json:"type"`
			} `json:"items"`
		} `json:"harddrives"`
		Hostname struct {
			Description string `json:"description"`
			Type        string `json:"type"`
		} `json:"hostname"`
		Kernels struct {
			Description string `json:"description"`
			Type        string `json:"type"`
			Items       struct {
				Type string   `json:"type"`
				Enum []string `json:"enum"`
			} `json:"items"`
		} `json:"kernels"`
		KeyboardLanguage struct {
			Description string `json:"description"`
			Type        string `json:"type"`
		} `json:"keyboard-language"`
		MirrorRegion struct {
			Description string `json:"description"`
			Type        string `json:"type"`
		} `json:"mirror-region"`
		NetworkConfig struct {
			Description string `json:"description"`
			Type        string `json:"type"`
			Properties  struct {
				Type string `json:"type"`
				Nics struct {
					Type  string `json:"type"`
					Items struct {
						Iface   string `json:"iface"`
						Dhcp    string `json:"dhcp"`
						IP      string `json:"ip"`
						Gateway string `json:"gateway"`
						DNS     struct {
							Description string `json:"description"`
							Type        string `json:"type"`
							Items       struct {
								Type string `json:"type"`
							} `json:"items"`
						} `json:"dns"`
					} `json:"items"`
				} `json:"nics"`
			} `json:"properties"`
		} `json:"network_config"`
		Ntp struct {
			Description string `json:"description"`
			Type        string `json:"type"`
		} `json:"ntp"`
		Packages struct {
			Description string `json:"description"`
			Type        string `json:"type"`
			Items       struct {
				Type string `json:"type"`
			} `json:"items"`
		} `json:"packages"`
		Profile struct {
			Path struct {
				Description string `json:"description"`
				Type        string `json:"type"`
			} `json:"path"`
			Main struct {
				Description string   `json:"description"`
				Type        string   `json:"type"`
				Enum        []string `json:"enum"`
			} `json:"main"`
			Details struct {
				Description string   `json:"description"`
				Type        string   `json:"type"`
				Enum        []string `json:"enum"`
			} `json:"details"`
			Custom struct {
				Description string `json:"description"`
				Type        string `json:"type"`
				Items       struct {
					Type       string `json:"type"`
					Properties struct {
						Packages string `json:"packages"`
						Services string `json:"services"`
						Enabled  string `json:"enabled"`
					} `json:"properties"`
				} `json:"items"`
			} `json:"custom"`
			GfxDriver struct {
				Description string   `json:"description"`
				Type        string   `json:"type"`
				Enum        []string `json:"enum"`
			} `json:"gfx_driver"`
			GreeterType struct {
				Description string   `json:"description"`
				Type        string   `json:"type"`
				Enum        []string `json:"enum"`
			} `json:"greeter_type"`
		} `json:"profile"`
		Services struct {
			Description string `json:"description"`
			Type        string `json:"type"`
			Items       struct {
				Type string `json:"type"`
			} `json:"items"`
		} `json:"services"`
		SysEncoding struct {
			Description string `json:"description"`
			Type        string `json:"type"`
		} `json:"sys-encoding"`
		SysLanguage struct {
			Description string `json:"description"`
			Type        string `json:"type"`
		} `json:"sys-language"`
		Timezone struct {
			Description string `json:"description"`
			Type        string `json:"type"`
		} `json:"timezone"`
	} `json:"properties"`
	Required []string `json:"required"`
	AnyOf    []struct {
		Required []string `json:"required"`
	} `json:"anyOf"`
}