config_version = "2.5.2"
additional-repositories = []
archinstall-language = "English"
bootloader = "Systemd-boot"
debug = false
hostname = "archlinux"
kernels = ["linux"]
keyboard-layout = "us"
no_pkg_lookups = false
ntp = true
offline = false
packages = []
"parallel downloads" = 0
script = "guided"
silent = false
swap = true
sys-encoding = "utf-8"
sys-language = "en_US"
timezone = "UTC"
version = "2.5.2"

[audio_config]
audio = "pipewire"

[disk_config]
config_type = "default_layout"

[[disk_config.device_modifications]]
device = "/dev/sda"
wipe = true

[[disk_config.device_modifications.partitions]]
btrfs = []
flags = ["Boot"]
fs_type = "fat32"
mount_options = []
mountpoint = "/boot"
obj_id = "2c3fa2d5-2c79-4fab-86ec-22d0ea1543c0"
status = "create"
type = "primary"

[disk_config.device_modifications.partitions.size]
unit = "MiB"
value = 512

[disk_config.device_modifications.partitions.start]
unit = "MiB"
value = 1

[[disk_config.device_modifications.partitions]]
btrfs = []
flags = []
fs_type = "ext4"
mount_options = []
mountpoint = "/"
obj_id = "3e7018a0-363b-4d05-ab83-8e82d13db208"
status = "create"
type = "primary"

[disk_config.device_modifications.partitions.size]
unit = "GiB"
value = 20

[disk_config.device_modifications.partitions.start]
unit = "MiB"
value = 513

[[disk_config.device_modifications.partitions]]
btrfs = []
flags = []
fs_type = "ext4"
mount_options = []
mountpoint = "/home"
obj_id = "ce58b139-f041-4a06-94da-1f8bad775d3f"
status = "create"
type = "primary"

[disk_config.device_modifications.partitions.size]
unit = "Percent"
value = 100

[disk_config.device_modifications.partitions.start]
unit = "GiB"
value = 20

[mirror-region.Australia]
"http://archlinux.mirror.digitalpacific.com.au/$repo/os/$arch" = true

[nic]
dhcp = true
type = "nm"

[profile_config]
gfx_driver = "All open-source (default)"
greeter = "sddm"

[profile_config.profile]
details = ["Kde"]
main = "Desktop"
